name: asdasdasd
on:
  push:

jobs:
  Publish:
    defaults:
      run:
        working-directory: boardgent-console
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          node-version: "10.15.3"
      - name: npm clear cache
        run: npm cache clear --force
      - name: npm install
      - name: run linter validation
        run: npm run lint
      - name: Publish to AWS
        run: npm run electron:publish
