name: asdasdasd
on:
  push:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "10.15.3"
      - name: npm clear cache
        run: npm cache clear --force
      - name: npm install
        run: npm i
      - name: Publish to AWS
        run: npm run release
